name       : gstreamer-1.0-plugins-base
version    : 1.18.4
release    : 39
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/archive/1.18.4/gst-plugins-base-1.18.4.tar.gz : 7ade65d9a9c88a346954aeea3133ffba89d90da7534895f1a960b26fa496d4ca
license    : LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gitlab.freedesktop.org/gstreamer/gst-plugins-base
summary    : GStreamer base plug-ins and elements
description: |
    The GStreamer Base Plug-ins is a well-groomed and well-maintained collection of GStreamer plug-ins and elements, spanning the range of possible types of elements one would want to write for GStreamer. You will need at least one of Good, Bad, Ugly or Libav plugins for GStreamer applications to function properly.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(ogg)
    - pkgconfig(opus)
    - pkgconfig(orc-0.4)
    - pkgconfig(pangocairo)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xv)
setup      : |
    %meson_configure -Dpackage-name="GStreamer Base Plugins ${version} Solus" \
        -Dpackage-origin="https://getsol.us" \
        -Dgobject-cast-checks=disabled \
        -Dglib-asserts=disabled \
        -Dglib-checks=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
